site_name: Propius
repo_name: dafevara/propius
repo_url: https://github.com/dafevara/propius
site_url: http://192.168.20.29/
nav:
- Overview: index.md
- Setup: setup.md
- Similarity Model: model.md
- Rest API: rest-api.md
- API Reference:
  - SimilarityModel: api/sim-model.md
  - ModelStorer: api/model-storing.md
  - Utils: api/utils.md
extra:
  search:
    language: en
  social:
  - icon: octicons/mark-github-16
    link: https://github.com/dafevara
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/dafevara
theme: material
markdown_extensions:
- codehilite:
    guess_lang: false
    use_pygments: true
    noclasses: true
    pygments_style: default
plugins:
- search
- mkdocstrings
